# Configuration générique pour une base de données unique.

[alembic]
# Chemin vers les scripts de migration.
# Ce chemin est généralement donné au format POSIX (ex: barres obliques inverses)
# relatif au token %(here)s qui fait référence à l'emplacement de ce fichier ini
script_location = %(here)s/alembic

# Modèle utilisé pour générer les noms de fichiers de migration; La valeur par défaut est %%(rev)s_%%(slug)s
# Décommentez la ligne ci-dessous si vous voulez que les fichiers soient préfixés avec la date et l'heure
# voir https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file
# pour tous les tokens disponibles
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# Chemin sys.path, sera ajouté au début de sys.path s'il est présent.
# Par défaut, il s'agit du répertoire de travail actuel. Pour plusieurs chemins, le séparateur
# est défini par "path_separator" ci-dessous.
prepend_sys_path = .

# Fuseau horaire à utiliser lors du rendu de la date dans le fichier de migration
# ainsi que le nom du fichier.
# Si spécifié, nécessite python>=3.9 ou la bibliothèque backports.zoneinfo et la bibliothèque tzdata.
# Toutes les dépendances requises peuvent être installées en ajoutant `alembic[tz]` aux exigences pip
# La valeur de chaîne est passée à ZoneInfo()
# Laissez vide pour l'heure locale
# timezone =

# Longueur maximale des caractères à appliquer au champ "slug"
# truncate_slug_length = 40

# Définir à 'true' pour exécuter l'environnement pendant
# la commande 'revision', quel que soit autogenerate
# revision_environment = false

# Définir à 'true' pour permettre aux fichiers .pyc et .pyo sans
# un fichier source .py d'être détectés comme révisions dans le
# répertoire versions/
# sourceless = false

# Spécification de l'emplacement des versions; Par défaut
# à <script_location>/versions. Lors de l'utilisation de plusieurs répertoires
# de version, les révisions initiales doivent être spécifiées avec --version-path.
# Le séparateur de chemin utilisé ici devrait être le séparateur spécifié par "path_separator"
# ci-dessous.
# version_locations = %(here)s/bar:%(here)s/bat:%(here)s/alembic/versions

# path_separator; Cela indique quel caractère est utilisé pour diviser les listes de chemins
# de fichiers, y compris version_locations et prepend_sys_path dans les fichiers configparser
# tels que alembic.ini.
# La valeur par défaut rendue dans les nouveaux fichiers alembic.ini est "os", qui utilise os.pathsep
# pour fournir un séparateur de chemin dépendant du système d'exploitation.
#
# Notez que pour prendre en charge les fichiers alembic.ini hérités, cette valeur par défaut NE prend PAS
# effet si path_separator n'est pas présent dans alembic.ini. Si cette
# option est omise entièrement, la logique de repli est la suivante:
#
# 1. L'analyse de l'option version_locations revient à utiliser la clé héritée
#    "version_path_separator", qui si absente revient alors au comportement hérité
#    de division sur les espaces et/ou les virgules.
# 2. L'analyse de l'option prepend_sys_path revient au comportement hérité
#    de division sur les espaces, les virgules ou les deux-points.
#
# Les valeurs valides pour path_separator sont:
#
# path_separator = :
# path_separator = ;
# path_separator = space
# path_separator = newline
#
# Utiliser os.pathsep. Configuration par défaut utilisée pour les nouveaux projets.
path_separator = os

# Définir à 'true' pour rechercher les fichiers source de manière récursive
# dans chaque répertoire "version_locations"
# nouveau dans Alembic version 1.10
# recursive_version_locations = false

# L'encodage de sortie utilisé lorsque les fichiers de révision
# sont écrits à partir de script.py.mako
# output_encoding = utf-8

# URL de base de données. Ceci est consommé par le script env.py maintenu par l'utilisateur uniquement.
# D'autres moyens de configurer les URL de base de données peuvent être personnalisés dans le fichier env.py.
sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks définit des scripts ou fonctions Python qui sont exécutés
# sur les scripts de révision nouvellement générés. Voir la documentation pour plus
# de détails et d'exemples

# Formater avec "black" - utiliser le runner console_scripts, contre l'entrypoint "black"
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# Linter avec tentatives de correction en utilisant "ruff" - utiliser le runner exec, exécuter un binaire
# hooks = ruff
# ruff.type = exec
# ruff.executable = %(here)s/.venv/bin/ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

# Configuration de journalisation. Ceci est également consommé par le script env.py maintenu par l'utilisateur uniquement.
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
