"""init

ID de révision: df8d922939d7
Révise: 
Date de création: 2026-06-01 01:29:19.243609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificateurs de révision, utilisés par Alembic.
revision: str = 'df8d922939d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Mettre à jour le schéma."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('email_verifie', sa.Boolean(), nullable=True),
    sa.Column('type_compte', sa.String(), nullable=True),
    sa.Column('palier', sa.String(), nullable=True),
    sa.Column('date_fin_abonnement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solde_candidatures', sa.Integer(), nullable=True),
    sa.Column('nom_entreprise', sa.String(), nullable=True),
    sa.Column('description_entreprise', sa.Text(), nullable=True),
    sa.Column('secteur_activite', sa.String(), nullable=True),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('site_web', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('avis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('donneur_id', sa.String(), nullable=True),
    sa.Column('receveur_id', sa.String(), nullable=True),
    sa.Column('collaboration_id', sa.String(), nullable=True),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donneur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['receveur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avis_id'), 'avis', ['id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('organisme', sa.String(), nullable=True),
    sa.Column('date_obtention', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url_certificat', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_table('codes_qr',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_codes_qr_id'), 'codes_qr', ['id'], unique=False)
    op.create_table('collaborations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('freelance_id', sa.String(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('zone_intervention', sa.String(), nullable=True),
    sa.Column('type_client', sa.String(), nullable=True),
    sa.Column('limite_temps', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prioritaire', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['freelance_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_id'), 'collaborations', ['id'], unique=False)
    op.create_table('competences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('niveau', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competences_id'), 'competences', ['id'], unique=False)
    op.create_table('cv',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('url_pdf', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_cv_id'), 'cv', ['id'], unique=False)
    op.create_table('diplomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('etablissement', sa.String(), nullable=True),
    sa.Column('annee_obtention', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diplomes_id'), 'diplomes', ['id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('entreprise', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_cours', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_table('profils',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('titre_professionnel', sa.String(), nullable=True),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('taux_horaire', sa.Float(), nullable=True),
    sa.Column('disponibilite', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('dribbble', sa.String(), nullable=True),
    sa.Column('portfolio', sa.String(), nullable=True),
    sa.Column('nombre_vues', sa.Integer(), nullable=True),
    sa.Column('score_popularite', sa.Float(), nullable=True),
    sa.Column('boost_visibilite', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_profils_id'), 'profils', ['id'], unique=False)
    op.create_table('projets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('images_urls', sa.Text(), nullable=True),
    sa.Column('url_projet', sa.String(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projets_id'), 'projets', ['id'], unique=False)
    op.create_index(op.f('ix_projets_utilisateur_id'), 'projets', ['utilisateur_id'], unique=False)
    op.create_table('scores_confiance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('nombre_avis', sa.Integer(), nullable=True),
    sa.Column('nombre_projets', sa.Integer(), nullable=True),
    sa.Column('verification_complete', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_scores_confiance_id'), 'scores_confiance', ['id'], unique=False)
    op.create_table('validations_sociales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('plateforme', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_sociales_id'), 'validations_sociales', ['id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_table('candidatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collaboration_id', sa.String(), nullable=False),
    sa.Column('freelance_id', sa.String(), nullable=False),
    sa.Column('message_motivation', sa.Text(), nullable=True),
    sa.Column('tarif_propose', sa.Float(), nullable=True),
    sa.Column('duree_estimee', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('prioritaire', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.ForeignKeyConstraint(['freelance_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collaboration_id', 'freelance_id', name='uq_candidature_collab_freelance')
    )
    op.create_index(op.f('ix_candidatures_collaboration_id'), 'candidatures', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_candidatures_freelance_id'), 'candidatures', ['freelance_id'], unique=False)
    op.create_index(op.f('ix_candidatures_id'), 'candidatures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annuler les modifications du schéma."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidatures_id'), table_name='candidatures')
    op.drop_index(op.f('ix_candidatures_freelance_id'), table_name='candidatures')
    op.drop_index(op.f('ix_candidatures_collaboration_id'), table_name='candidatures')
    op.drop_table('candidatures')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_validations_sociales_id'), table_name='validations_sociales')
    op.drop_table('validations_sociales')
    op.drop_index(op.f('ix_scores_confiance_id'), table_name='scores_confiance')
    op.drop_table('scores_confiance')
    op.drop_index(op.f('ix_projets_utilisateur_id'), table_name='projets')
    op.drop_index(op.f('ix_projets_id'), table_name='projets')
    op.drop_table('projets')
    op.drop_index(op.f('ix_profils_id'), table_name='profils')
    op.drop_table('profils')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_diplomes_id'), table_name='diplomes')
    op.drop_table('diplomes')
    op.drop_index(op.f('ix_cv_id'), table_name='cv')
    op.drop_table('cv')
    op.drop_index(op.f('ix_competences_id'), table_name='competences')
    op.drop_table('competences')
    op.drop_index(op.f('ix_collaborations_id'), table_name='collaborations')
    op.drop_table('collaborations')
    op.drop_index(op.f('ix_codes_qr_id'), table_name='codes_qr')
    op.drop_table('codes_qr')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_avis_id'), table_name='avis')
    op.drop_table('avis')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
